spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=user_mangement_db
    username: appuser
    password: apppassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092 # address of Kafka broker

    producer: # producer-specific configurations
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # key serializer class
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # value serializer class for JSON
      acks: all # ensure message durability, all means all replicas must acknowledge the message
      retries: 3 # number of retries on failure to send a message

    consumer: # consumer-specific configurations
      group-id: user-service-group # consumer group id for load balancing, all instances with same group id share the load
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # key deserializer class
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # value deserializer class for JSON
      auto-offset-reset: earliest # start consuming from the earliest message if no offset is present
      properties:
        spring.json.trusted.packages: "*" # trust all packages for JSON deserialization


resilience4j:
  retry: # retry configuration is used to automatically retry failed operations
    instances:
      userRegistrationRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException

  ratelimiter: # rate limiter configuration is used to limit the rate of requests to a service to prevent overload
    instances:
      userRegistrationRateLimiter:
        limit-for-period: 100
        limit-refresh-period: 60s
        timeout-duration: 0
        subscribe-for-events: true

management:
  health:
    circuitbreakers:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info



server:
  port: 7001


eureka:
    client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
