spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=product_db
    username: appuser
    password: apppassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: product-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 7002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


resilience4j:
  retry:
    instances:
      productUpdateRetry:
        maxAttempts: 2
        waitDuration: 500ms

  ratelimiter:
    instances:
      productListingRateLimiter:
        limitForPeriod: 200
        limitRefreshPeriod: 1m
        timeoutDuration: 0

  bulkhead:
    instances:
      inventoryBulkhead:
        maxConcurrentCalls: 10
        maxWaitDuration: 0


management:
  health:
    circuitbreakers:
      enabled: false  # no external circuitbreaker for this service
  endpoints:
    web:
      exposure:
        include: health,info
