spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=product_db
    username: appuser
    password: apppassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: product-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 7002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


resilience4j:
  retry: # retry configuration is used to automatically retry failed operations
    instances:
      productUpdateRetry:
        max-attempts: 2
        wait-duration: 300ms
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException

  ratelimiter: # rate limiter configuration is used to limit the rate of requests to a service to prevent overload
    instances:
      productListRateLimiter:
        limit-for-period: 200 # allow 200 requests per period
        limit-refresh-period: 60s # period duration of 60 seconds
        timeout-duration: 0
        subscribe-for-events: true

  bulkhead: # bulkhead configuration is used to limit the number of concurrent calls to a service to prevent overload, isolating failures
    instances:
      inventoryBulkhead:
        max-concurrent-calls: 10 # limit to 10 calls at a time to inventory service
        max-wait-duration: 0 # do not wait if bulkhead is full
        writable-stack-trace-enabled: false


management:
  health:
    circuitbreakers:
      enabled: false  # no external circuitbreaker for this service
  endpoints:
    web:
      exposure:
        include: health,info
