spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=cart_db
    username: appuser
    password: apppassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: cart-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 7003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


resilience4j:
  circuitbreaker:
    instances:
        cartServiceCircuitBreaker: # Name of the circuit breaker instance to be used when calling order service from cart service
            registerHealthIndicator: true
            slidingWindowSize: 10 # Number of calls to consider for the circuit breaker
            minimumNumberOfCalls: 6 # Minimum number of calls before calculating failure rate
            failureRateThreshold: 50 # Percentage of failures to open the circuit
            waitDurationInOpenState: 10000 # Time to wait before transitioning from open to half-open state (in milliseconds)
            permittedNumberOfCallsInHalfOpenState: 3  # Number of calls allowed in half-open state
        kafkaCircuitBreaker: # we need this because we are calling kafka producer inside cart service
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 3
            failureRateThreshold: 50
            waitDurationInOpenState: 5000 # in milliseconds
            permittedNumberOfCallsInHalfOpenState: 3

  retry:
    instances:
      cartServiceRetry: # this name will be used in the annotation in the service class of cart service
        maxAttempts: 3
        waitDuration: 2000 # in milliseconds
        exponentialBackoffMultiplier: 2
        # Retry on all exceptions by default, can be customized further if needed



