spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=cart_db
    username: appuser
    password: apppassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: cart-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 7003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/




# Services URLs :
services:
  product-service:
    url: http://PRODUCT-SERVICE
  payment-service:
    url: http://PAYMENT-SERVICE
  user-service:
    url: http://USER-SERVICE
  order-service:
    url: http://ORDER-SERVICE
  cart-service:
    url: http://CART-SERVICE
  shipping-service:
    url: http://SHIPPING-SERVICE


resilience4j:
  circuitbreaker:
    instances:
        kafkaCircuitBreaker: # we need this because we are calling kafka producer inside cart service
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 3
            failureRateThreshold: 50
            waitDurationInOpenState: 5000 # in milliseconds
            permittedNumberOfCallsInHalfOpenState: 3
        orderServiceCircuitBreaker:
          registerHealthIndicator: true
          slidingWindowSize: 10
          minimumNumberOfCalls: 6
          failureRateThreshold: 50
          waitDurationInOpenState: 10000
          permittedNumberOfCallsInHalfOpenState: 3


  retry:
    instances:
      cartServiceRetry: # this name will be used in the annotation in the service class of cart service
        maxAttempts: 3
        waitDuration: 2000 # in milliseconds
        exponentialBackoffMultiplier: 2
        # Retry on all exceptions by default, can be customized further if needed





